#!/bin/bash

# Debian + Hugo
build "debian" - \
  "[version]-debian"

# Debian + Hugo + Onbuild
#template onbuild debian-onbuild debian
build "debian-onbuild" "debian--onbuild" \
  "[version]-debian-onbuild"
