FROM klakegg/hugo:base AS base

FROM klakegg/hugo:base-certs as certs



FROM scratch as image

COPY --from=base /alpine /
COPY --from=base /hugo-standard /
COPY --from=certs / /



FROM alpine:3.11

ENV HUGO_BIND="0.0.0.0" \
    HUGO_DESTINATION="public" \
    HUGO_ENV="DEV" \
    HUGO_EDITION="standard" \
    HOME="/tmp"

COPY --from=image / /

RUN apk --no-cache add busybox-suid bash bash-completion tzdata make \
 && find /tmp -mindepth 1 -maxdepth 1 | xargs rm -rf \
 && mkdir -p /src /target \
 && chmod a+w /src /target

EXPOSE 1313

WORKDIR /src

ENTRYPOINT ["hugo"]
