#!/bin/bash

# Alpine + Hugo
build "alpine" - \
  "[version]-alpine"

# Alpine + Hugo + Onbuild
build "alpine-onbuild" "alpine--onbuild" \
  "[version]-alpine--onbuild"

# Alpine + Hugo + Asciidoctor
build "asciidoctor" - \
  "[version]-asciidoctor"

# Alpine + Hugo + Asciidoctor + Onbuild
build "asciidoctor-onbuild" "asciidoctor--onbuild" \
  "[version]-asciidoctor-onbuild"

# Alpine + Hugo + Pandoc
build "pandoc" - \
  "[version]-pandoc"

# Alpine + Hugo + Pandoc + Onbuild
build "pandoc-onbuild" "pandoc--onbuild" \
  "[version]-pandoc-onbuild"
