#!/bin/bash

test "alpine" "" "version" "Hugo"

test "asciidoctor" "--entrypoint asciidoctor" "--version" "Asciidoctor 2"

test "pandoc" "--entrypoint pandoc-default" "--version" "Compiled with pandoc"
