#!/bin/bash

# Alpine + Hugo
build alpine
tag   alpine "[version]-alpine"

# Alpine + Hugo + Onbuild
template onbuild alpine-onbuild alpine
build alpine-onbuild
tag   alpine-onbuild "[version]-alpine-onbuild"

# Alpine + Hugo + Asciidoctor
build asciidoctor
tag   asciidoctor "[version]-asciidoctor"

# Alpine + Hugo + Asciidoctor + Onbuild
template onbuild asciidoctor-onbuild asciidoctor
build asciidoctor-onbuild
tag   asciidoctor-onbuild "[version]-asciidoctor-onbuild"

# Alpine + Hugo + Pandoc
build pandoc
tag   pandoc "[version]-pandoc"

# Alpine + Hugo + Pandoc + Onbuild
template onbuild pandoc-onbuild pandoc
build pandoc-onbuild
tag   pandoc-onbuild "[version]-pandoc-onbuild"

# Alpine + Hugo extended
build ext-alpine
tag   ext-alpine "[version]-ext-alpine"

# Alpine + Hugo extended + Onbuild
template onbuild ext-alpine-onbuild ext-alpine
build ext-alpine-onbuild
tag   ext-alpine-onbuild "[version]-ext-alpine-onbuild"

# Alpine + Hugo extended + Asciidoctor
build ext-asciidoctor
tag   ext-asciidoctor "[version]-ext-asciidoctor"

# Alpine + Hugo extended + Asciidoctor + Onbuild
template onbuild ext-asciidoctor-onbuild ext-asciidoctor
build ext-asciidoctor-onbuild
tag   ext-asciidoctor-onbuild "[version]-ext-asciidoctor-onbuild"
