#!/bin/bash

# Alpine + Hugo
build alpine Dockerfile-alpine
tag   alpine "[version]-alpine"

# Alpine + Hugo + Onbuild
build alpine-onbuild Dockerfile-alpine-onbuild
tag   alpine-onbuild "[version]-alpine-onbuild"

# Alpine + Hugo + Asciidoctor
build asciidoctor Dockerfile-asciidoctor
tag   asciidoctor "[version]-asciidoctor"

# Alpine + Hugo + Asciidoctor + Onbuild
build asciidoctor-onbuild Dockerfile-asciidoctor-onbuild
tag   asciidoctor-onbuild "[version]-asciidoctor-onbuild"

# Alpine + Hugo + Pandoc
build pandoc Dockerfile-pandoc
tag   pandoc "[version]-pandoc"

# Alpine + Hugo + Pandoc + Onbuild
build pandoc-onbuild Dockerfile-pandoc-onbuild
tag   pandoc-onbuild "[version]-pandoc-onbuild"

# Alpine + Hugo extended
build ext-alpine Dockerfile-ext-alpine
tag   ext-alpine "[version]-ext-alpine"

# Alpine + Hugo extended + Onbuild
build ext-alpine-onbuild Dockerfile-ext-alpine-onbuild
tag   ext-alpine-onbuild "[version]-ext-alpine-onbuild"

# Alpine + Hugo extended + Asciidoctor
build ext-asciidoctor Dockerfile-ext-asciidoctor
tag   ext-asciidoctor "[version]-ext-asciidoctor"

# Alpine + Hugo extended + Asciidoctor + Onbuild
build ext-asciidoctor-onbuild Dockerfile-ext-asciidoctor-onbuild
tag   ext-asciidoctor-onbuild "[version]-ext-asciidoctor-onbuild"
