FROM alpine:3.7 AS fetch

ARG VERSION=0.43

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_Linux-64bit.tar.gz /hugo.tar.gz
RUN tar -zxvf hugo.tar.gz



FROM ubuntu:18.04 AS ubuntu



FROM frolvlad/alpine-glibc:alpine-3.7

ENV HUGO_BIND="0.0.0.0" \
    HUGO_DESTINATION="/target"

COPY --from=fetch /hugo /bin/hugo
COPY files /

RUN apk add --no-cache libstdc++
COPY --from=ubuntu /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25 /usr/lib/libstdc++.so.6

EXPOSE 1313

VOLUME /src /target
WORKDIR /src

ENTRYPOINT ["sh", "/run.sh"]
