FROM busybox:1.30 AS fetch-standard

ARG VERSION=0.58.1

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz /hugo.tar.gz
RUN tar -zxvf hugo.tar.gz
RUN ["/hugo", "version"]



FROM busybox:1.30 AS fetch-extended

ARG VERSION=0.58.1

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_Linux-64bit.tar.gz /hugo.tar.gz
RUN tar -zxvf hugo.tar.gz



FROM busybox:1.30 AS files

COPY --from=fetch-standard /hugo /files/hugo-standard/bin/hugo-official
COPY --from=fetch-extended /hugo /files/hugo-extended/bin/hugo-official

ADD dist/alpine/files /files/alpine
ADD dist/busybox/files /files/busybox
ADD dist/debian/files /files/debian
ADD dist/ubuntu/files /files/ubuntu

RUN chmod a+x /files/*/bin/* && find /files -type f


FROM scratch

COPY --from=files /files /
