FROM busybox:1.31 AS fetch

ARG VERSION=0.71.0

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz /
ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_Linux-64bit.tar.gz /
ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_checksums.txt /

# Verify checksums
RUN grep Linux-64bit.tar.gz hugo_${VERSION}_checksums.txt | sha256sum -c

# Unpack downloaded content
RUN mkdir /hugo-standard /hugo-extended
RUN tar -zxf hugo_${VERSION}_Linux-64bit.tar.gz -C /hugo-standard
RUN tar -zxf hugo_extended_${VERSION}_Linux-64bit.tar.gz -C /hugo-extended

# Verify executable
RUN ["/hugo-standard/hugo", "version"]

# Create autocompletion script
RUN mkdir /etc/bash_completion.d  \
 && /hugo-standard/hugo gen autocomplete > /dev/null



FROM busybox:1.31 AS files

COPY --from=fetch /hugo-standard/hugo /files/hugo-standard/bin/hugo-official
COPY --from=fetch /hugo-extended/hugo /files/hugo-extended/bin/hugo-official

COPY --from=fetch /hugo-standard/LICENSE /files/hugo-standard/LICENSE
COPY --from=fetch /hugo-extended/LICENSE /files/hugo-extended/LICENSE

COPY --from=fetch /hugo-standard/README.md /files/hugo-standard/README.md
COPY --from=fetch /hugo-extended/README.md /files/hugo-extended/README.md

COPY --from=fetch /etc/bash_completion.d/hugo.sh /files/hugo-standard/etc/bash_completion.d/hugo.sh
COPY --from=fetch /etc/bash_completion.d/hugo.sh /files/hugo-extended/etc/bash_completion.d/hugo.sh

ADD src/dist/alpine/files /files/alpine
ADD src/dist/busybox/files /files/busybox
ADD src/dist/debian/files /files/debian
ADD src/dist/ubuntu/files /files/ubuntu

RUN chmod a+x /files/*/bin/* \
 && mkdir -p /files/hugo-{standard,extended}/{src,target} \
 && chmod a+w /files/hugo-{standard,extended}/{src,target} \
 && find /files -type f | sort



FROM scratch

COPY --from=files /files /
