#!/bin/bash

# Ubuntu + Hugo extended
build "ext-ubuntu" - \
  "[version]-ext-ubuntu"

# Ubuntu + Hugo extended + Onbuild
template onbuild ext-ubuntu-onbuild ext-ubuntu
build "ext-ubuntu-onbuild" - \
  "[version]-ext-ubuntu-onbuild"
