#!/bin/bash

# Busybox + Hugo
build "busybox" - \
  "latest" \
  "[version]" \
  "[version]-busybox"

# Busybox + Hugo + Onbuild
#template onbuild busybox-onbuild busybox
build "busybox-onbuild" "busybox--onbuild" \
  "[version]-busybox-onbuild" \
  "[version]-onbuild" \
  "onbuild"
