#!/bin/bash

source ../tools/docker_hub.sh

# Ubuntu + Hugo
#build ubuntu Dockerfile-ubuntu
tag   ubuntu "[version]-ubuntu"

# Ubuntu + Hugo + Onbuild
build ubuntu-onbuild Dockerfile-ubuntu-onbuild
tag   ubuntu-onbuild "[version]-ubuntu-onbuild"

# Ubuntu + Hugo extended
build ext-ubuntu Dockerfile-ext-ubuntu
tag   ext-ubuntu "ext"
tag   ext-ubuntu "ext-latest"
tag   ext-ubuntu "[version]-ext-ubuntu"

# Ubuntu + Hugo extended + Onbuild
build ext-ubuntu-onbuild Dockerfile-ext-ubuntu-onbuild
tag   ext-ubuntu-onbuild "[version]-ext-ubuntu-onbuild"
tag   ext-ubuntu-onbuild "[version]-ext-onbuild"
tag   ext-ubuntu-onbuild "ext-onbuild"
