#!/bin/bash

# This is the file triggered by Docker Hub after building the initial image.

DPWD=$(pwd)
PART="sys"
PATH="$(dirname $(dirname $(realpath $0)))/bin:$PATH"
TARGET=$(__repo_path)/target

# tag [intial tag] [extra tag]
function tag {
  # Perform tagging
  echos "Tag:   $1 => $(real $2)"
  _docker tag $DOCKER_REPO:$1 $DOCKER_REPO:$(real $2)

  # Push tag
  push $2
}

# build [inital tag] [Dockerfile extension] [extra tags...]
function build {
  # Perform build
  build_only $1 $2

  # Push build
  push $1

  # Add extra tags
  for t in ${@:3}; do
    tag $1 "$t"
  done
}

# build_only [initial tag] [Dockerfile extension]
function build_only {
  # Detect Dockerfile extension if not set.
  name=$2
  if [ "$2" = "" ] || [ "$2" = "-" ]; then
    if [ -e "Dockerfile-gen-$1" ]; then
      name="gen-$1"
    else
      name=$1
    fi
  fi

  # Perform build
  echos "Build: $1 (Dockerfile-$name)"
  _docker buildx build \
    --no-cache \
    --output "type=docker" \
    --progress plain \
    --tag $DOCKER_REPO:$1 \
    --file Dockerfile-$name \
    ${DPWD}/files
}

# push [tag]
function push {
  # Figure out full image identififer.
  img=$DOCKER_REPO:$(real $1)

  if [ "$CI" != "true" ]; then
    # Acually push when not in a CI environment.
    echos "       Push: $img"
    _docker push $img
  else
    # Simple logging in CI environment with debug enabled.
    if [ "${DEBUG:-false}" = "true" ]; then
      echos "       Push: $img (skipped)"
    fi

    echo $img >> $TARGET/tags
  fi
}

# real [tag]
function real {
  echo $1 | sed -e "s/\[version\]/${SOURCE_BRANCH}/g"
}

# template [tp] [target] [from]
function template {
  cat $DPWD/docker/_template/Dockerfile-$1 \
  | sed -e "s|\[from\]|${DOCKER_REPO}:${3}|g" \
  > Dockerfile-gen-$2
}

# trigger [dir]
function trigger {
  # Go to folder
  cd $DPWD/docker/$1

  if [ ! -e ".skip" ]; then
    # Trigger steps
    for step in "build" "test"; do
      if [ -e "Step-$step" ]; then
        PART="$1:$step"

        source "Step-$step"
        echo
      fi
    done
  fi
}

function test {
  echos "TEST: $@"

  if [ "${DOCKER_DEBUG:-false}" = "false" ]; then
    result=$(_docker run --rm $2 $DOCKER_REPO:$1 $3)
    count=$(echo $result | grep "$4" | wc -l)

    if [ "$count" = "0" ]; then
      echos "> FAILED: Expected \"$4\", received:"
      echos $result

      exit 1
    else
      echos "> SUCCESS"
    fi
  fi
}

function echos {
  echo "[$PART] $@"
}


# Listing some useful commands
echos "CI: $CI"
echos "DOCKER_REPO: $DOCKER_REPO"
echos "SOURCE_BRANCH: $SOURCE_BRANCH"
echos "TARGET: $TARGET"
echo

# Prepare tags file
mkdir -p $TARGET
rm -f $TARGET/tags

# Build distributions provided
for dist in ${DISTS:-$(ls $DPWD/docker | grep ^_) $(ls $DPWD/docker | grep ^[^_])}; do
  trigger $dist
done
