#!/bin/bash

# This is the file triggered locally in a CI environment or for local testing.

set -e

# Setting variables for build
export DOCKER_REPO="klakegg/hugo"
export SOURCE_BRANCH=$(cat lib/base/Dockerfile-base | grep VERSION | head -1 | cut -d = -f 2)
export CI="true"
export DEBUG="${DEBUG:-false}"

# Trigger code for Docker Hub
source hooks/build

# List images
docker images $DOCKER_REPO
echo
