#!/bin/bash

# This is the file triggered locally in a CI environment or for local testing.

set -e

# Setting variables for build
export DOCKER_REPO="klakegg/hugo"
export SOURCE_BRANCH=$(__version)
export CI="true"
export DEBUG="${DEBUG:-false}"

# Trigger code for Docker Hub
source hooks/build

# List images
_docker images $DOCKER_REPO
echo
