#!/bin/bash

DPWD=$(pwd)

# Listing some useful commands
echo "CI: $CI"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "SOURCE_BRANCH: $SOURCE_BRANCH"
echo

# Make sure only tagged commits triggers logic in hooks files.
if [ "$SOURCE_BRANCH" = "master" ]; then
    exit
fi

function tag {
  echo "Tag:   $1 => $(real $2)"
  docker tag $DOCKER_REPO:$1 $DOCKER_REPO:$(real $2)
  push $2
}

function build {
  build_only $1 $2
  echo -n "       Verification: "
  docker run --rm $DOCKER_REPO:$1 version
  push $1
}

function build_only {
  echo "Build: $1 ($2)"
  docker build -t $DOCKER_REPO:$1 -f $2 . > /dev/null
}

function push {
  img=$DOCKER_REPO:$(real $1)
  if [ "$CI" != "true" ]; then
    echo "       Push: $img"
    docker push $img > /dev/null
  else
    if [ "$DEBUG" = "true" ]; then
      echo "       Push: $img (skipped)"
    fi
  fi
}

function real {
  echo $1 | sed -e "s/\[version\]/${SOURCE_BRANCH}/g"
}


tag base "[version]-base"
echo

for VARIANT in "lib" "alpine" "busybox" "debian" "ubuntu"; do

  # Move to variant folder
  cd $DPWD/$VARIANT

  # Trigger hooks
  source config
  echo

done

# List images
docker images $DOCKER_REPO
echo
