#!/bin/bash

# This is the file triggered by Travis.

# Setting variables for build
export DOCKER_REPO="klakegg/hugo"
export SOURCE_BRANCH=$(cat Dockerfile-base  | grep VERSION | head -1 | cut -d = -f 2)
export CI="true"
export DEBUG="false"

# Build initial image as done by Docker Hub
docker build -t $DOCKER_REPO:base -f Dockerfile-base .
echo

# Trigger code for Docker Hub
source hooks/post_push

# List images
docker images $DOCKER_REPO
echo
