#!/bin/bash

# This is the file triggered by Travis.

# Setting variables for build
export DOCKER_REPO="klakegg/hugo"
export SOURCE_BRANCH="0.xx"
export CI="true"

# Build initial image as done by Docker Hub
docker build -t klakegg/hugo:base -f Dockerfile-base .
echo

# Trigger code for Docker Hub
source hooks/post_push

# List images
docker images $DOCKER_REPO
echo
