FROM alpine:3.11 AS fetch

ARG VERSION=0.73.0

ADD _script/hugo.sh hugo.sh
RUN sh hugo.sh



FROM busybox:1.31 AS files

# Copy content of files folder to populate base image
ADD . /files

# Copy Hugo files
COPY --from=fetch /hugo-standard /files/hugo-standard
COPY --from=fetch /hugo-extended /files/hugo-extended

RUN chmod a+x /files/*/bin/* \
 && rm -rf /files/_script \
 && find /files | sed s:^/files::g | sort



FROM scratch

# Create prepared files to root of base image
COPY --from=files /files /
