FROM klakegg/hugo:base AS base



FROM busybox:1.28

ENV HUGO_BIND="0.0.0.0" \
    HUGO_DESTINATION="/target"

COPY --from=base /bin/hugo-extended /bin/hugo
COPY files /

EXPOSE 1313

VOLUME /src /target
WORKDIR /src

ENTRYPOINT ["sh", "/run.sh"]
