FROM busybox:1.28 AS fetch

ARG NODE_VERSION=11.10.0
ARG ARCH=x64

ADD https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-${ARCH}.tar.xz /
RUN mkdir /node
RUN tar -xJf "node-v${NODE_VERSION}-linux-${ARCH}.tar.xz" -C /node --strip-components=1 --no-same-owner
RUN rm "node-v${NODE_VERSION}-linux-${ARCH}.tar.xz"

FROM scratch

COPY --from=fetch /node /node