FROM klakegg/hugo:base AS base

FROM klakegg/hugo:base-certs as certs

FROM ubuntu:18.04 AS ubuntu

FROM klakegg/hugo:base-nodejs as node

FROM klakegg/hugo:base-golang as golang



FROM scratch as image

COPY --from=base /alpine /
COPY --from=base /hugo-extended /
COPY --from=certs / /
COPY --from=node / /
COPY --from=golang / /
COPY --from=ubuntu /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25 /usr/lib/libstdc++.so.6



FROM frolvlad/alpine-glibc:alpine-3.11_glibc-2.30

ENV HUGO_BIND="0.0.0.0" \
    HUGO_DESTINATION="public" \
    HUGO_ENV="DEV" \
    HUGO_EDITION="extended" \
    HUGO_CACHEDIR="/tmp" \
    NODE_PATH=".:/lib/node_modules" \
    GOROOT="/usr/local/lib/go" \
    HOME="/tmp"

RUN apk add --no-cache libstdc++ busybox-suid bash bash-completion git tzdata make

COPY --from=image / /

RUN npm install -g yarn@1.22.4 autoprefixer postcss-cli @babel/cli @babel/core  \
 && find /tmp -mindepth 1 -maxdepth 1 | xargs rm -rf \
 && mkdir -p /src /target \
 && chmod a+w /src /target

EXPOSE 1313

WORKDIR /src

ENTRYPOINT ["hugo"]
