#!/bin/bash

# Debian + Hugo extended
build "ext-debian" - \
  "ext" \
  "latest-ext" \
  "[version]-ext" \
  "[version]-ext-debian"

# Debian + Hugo extended + Onbuild
build "ext-debian-onbuild" "ext-debian--onbuild" \
  "[version]-ext-debian-onbuild" \
  "[version]-ext-onbuild" \
  "ext-onbuild"
